### PR TITLE
Realign golden signal metrics for honeycomb to provide a traffic_type field

### PR DESCRIPTION
**Pull request by jdcasey**
I've been looking at the way we're reporting fields to honeycomb, and it's hard to aggregate / slice / group traffic. The reason is that we're publishing the SLI fields in the same way we do APM metric fields. This patch allows us to:

* Rely on the http_status for the error metric
* Rely on latency_ms for the latency on the method call
* Use the event count inherent in the Honeycomb/Opentracing approach to provide out load / throughput metrics
* Provide a new, single field that collapses the SLI metric names into a list of strings that we can filter on

This will collapse:
```
content.metadata
content.metadata.maven
```

into a single field called traffic_type with the following value:
```
content,metadata,maven
```

This way we can use GROUP BY to see multiple types of traffic on a single graph, or use WHERE ... CONTAINS(..) to filter on a specific type of traffic. Using these types of things, we can look at all maven traffic, all metadata traffic, all content traffic, or something specific.

To work, we need to upgrade Indy *and* galley-transport-httpclient (I found that out the hard way). Both Galley and Indy have some API inconsistencies with o11yphant 1.4-SNAPSHOT.

I haven't tested this yet, because I am currently having trouble arriving at the right configuration to push metrics to honeycomb. I'm still working on it...

We need to work on something like this soon, so we can move our support work over to using honeycomb instead of Grafana.

### CODE REVIEW

**Review by ruhan1 — APPROVED** [review]
LGTM

**Review by ligangty — APPROVED** [review]
LGTM

**Comment by yma88** [comment]
LGTM

**Comment by yma88** [comment]
I also met one galley inconsistency issue and blocked indy build when o11 honeycomb-core/api was involved, as galley(galley-transport-httpclient:1.5) depends on o11 old version, o11yphant-honeycomb:jar:1.0 will be in the shaded jar, some wrong version classes will be built out then. I push https://github.com/Commonjava/galley/pull/362 to fix.

@jdcasey One ques: this PR is fixed for only server metrics sending? Other services like current Client metrics already removes the dependency on o11 honey core: GoldenSignalsRootSpanFields.

**Comment by jdcasey** [comment]
@yma88 I think we might need to revisit this idea on the client API side, since I didn't have your changes in front of me to review / adjust at the time. I'll merge this one and we can continue the minor adjustments to these things as needed.

**Pull request merged**
