### PR TITLE
Fix: make honeycomb span more thread-safe

### PR DESCRIPTION
**Pull request by ligangty**
We found some ConcurrentModificationException during the service
   testing which happened in o11yphant tracing with weft thread context
   span operations. After checking, we found that it is caused by
   underlying honeycomb beeline library. Its span implementation is not
   thread safe.(See
   https://github.com/honeycombio/beeline-java/blob/v1.5.1/beeline-core/src/main/java/io/honeycomb/beeline/tracing/Span.java#L20)
   So this PR will do some thread safe protection in HoneycombSpan
   level.

### CODE REVIEW

**Review by ruhan1 — COMMENTED** [review]
will ConcurrentHashMap be enough?

**Comment by ligangty** [comment]
> will ConcurrentHashMap be enough?

As the underlying honeycomb beeline Span is using a HashMap to store its fields, so that means all the fields write operation is not thread safe. That's why I'm adding the synchronized primitive for the span write operations.

**Comment by ligangty** [comment]
@ruhan1 @jdcasey @sswguo @yma88 Can you help review this? I think this is blocking the usage of honeycomb tracing in Indy-monolith from weft thread pool level(If we enable the tracing in indy-monolith, like what we're doing now in ocp-c2). 

Or maybe the honeycomb native lib is not a good option for usage, and we should think about to switch to otel lib instead.

**Review by jdcasey — APPROVED** [review]
This looks good to me, though I'm not sure how it will affect performance. I started looking at the Otel SDK implementation of Span to see if it was threadsafe, but ran out of time. I doubt it is...that would be a pretty edge-case kind of thing to put into it, since (I believe) they are using ThreadLocals to keep spans with their threads.

**Comment by jdcasey** [comment]
In terms of whether ConcurrentHashMap is enough, that inProgress field is for cumulative counts...it's not a normal part of span attribute collection from a Honeycomb / Otel perspective, it's part of the cumulative counts / time stuff we did before. IMO we could almost just leave that out if we need to, but the ConcurrentHashMap is probably ok too.

**Comment by ligangty** [comment]
@jdcasey IIRC the otel Span is thread-safe. See: https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/Span.java#L28
That's why I'm thinking to switch to use otel lib instead of honeycomb native now. I'll try to test it in our IT environment with microservice. 
FWIW, I'll merge this one.

**Pull request merged**
